# Generated by Django 4.1.7 on 2023-03-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSDI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, null=True)),
                ('county', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('streetNumber', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='authorbook',
            name='contributionTime',
            field=models.IntegerField(null=True, verbose_name='(weeks)'),
        ),
        migrations.AddField(
            model_name='authorbook',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary Author'), ('secondary', 'Co-Author')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(null=True, verbose_name='Date of Birth(mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='authorbook',
            name='authorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSDI.author'),
        ),
        migrations.AlterField(
            model_name='authorbook',
            name='bookID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSDI.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisherID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSDI.publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='foundingYear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectSDI.address'),
        ),
    ]
