# Generated by Django 4.1.7 on 2023-03-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=200, null=True)),
                ('areaOfInterest', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('foundingYear', models.DateField()),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('webAddress', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('nrOfPages', models.IntegerField(null=True)),
                ('releaseYear', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=200, null=True)),
                ('publisherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectSDI.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectSDI.author')),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectSDI.book')),
            ],
        ),
    ]
