# Generated by Django 4.1.7 on 2023-03-26 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSDI', '0002_address_authorbook_contributiontime_authorbook_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='nrOfPages',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='releaseYear',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
